export const usersData = [
  {
    id: "1",
    name: "Mark Webber",
    userImg: "/avatar-mark-webber.webp",
    action: [
      {
        reaction: true,
        followed: false,
        joined: false,
        directMessage: false,
        message: "",
        commented: false,
        enteredgroup: false,
        leftgroup: false,
      },
    ],
    actiondate: new Date("January 31, 2023 11:19:00"),
    viewed: false,
  },
  {
    id: "2",
    name: "Angela Gray",
    userImg: "/avatar-angela-gray.webp",
    action: [
      {
        reaction: false,
        followed: true,
        joined: false,
        directMessage: false,
        message: "",
        commented: false,
        enteredgroup: false,
        leftgroup: false,
      },
    ],
    actiondate: new Date("January 28, 2023 14:23:00"),
    viewed: false,
  },
  {
    id: "3",
    name: "Jacob Thompson",
    userImg: "/avatar-jacob-thompson.webp",
    action: [
      {
        reaction: false,
        followed: false,
        joined: true,
        directMessage: false,
        message:
          "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game",
        commented: false,
        enteredgroup: false,
        leftgroup: false,
      },
    ],
    actiondate: new Date("January 24, 2023 14:23:00"),
    viewed: false,
  },
  {
    id: "4",
    name: "Rizky Hasanuddin",
    userImg: "/avatar-rizky-hasanuddin.webp",
    action: [
      {
        reaction: false,
        followed: false,
        joined: false,
        directMessage: true,
        message:
          "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game",
        commented: false,
        enteredgroup: false,
        leftgroup: false,
      },
    ],
    actiondate: new Date("January 29, 2023 14:23:00"),
    viewed: false,
  },
  {
    id: "5",
    name: "Kimberly Smith",
    userImg: "/avatar-kimberly-smith.webp",
    action: [
      {
        reaction: false,
        followed: false,
        joined: false,
        directMessage: false,
        message: "",
        commented: true,
        enteredgroup: false,
        leftgroup: false,
      },
    ],
    actiondate: new Date("January 29, 2023 14:23:00"),
    viewed: false,
  },
  {
    id: "6",
    name: "Nathan Peterson",
    userImg: "/avatar-nathan-peterson.webp",
    action: [
      {
        reaction: false,
        followed: false,
        joined: false,
        directMessage: false,
        message: "",
        commented: false,
        enteredgroup: true,
        leftgroup: false,
      },
    ],
    actiondate: new Date("January 29, 2023 14:23:00"),
    viewed: false,
  },
  {
    id: "7",
    name: "Anna Kim",
    userImg: "/avatar-anna-kim.webp",
    action: [
      {
        reaction: false,
        followed: false,
        joined: false,
        directMessage: false,
        message: "",
        commented: false,
        enteredgroup: false,
        leftgroup: true,
      },
    ],
    actiondate: new Date("January 29, 2023 14:23:00"),
    viewed: false,
  },
];
